#:schema node_modules/wrangler/config-schema.json
name                   = "demo-ai-db-query"
compatibility_date     = "2024-11-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[ai]
binding = "AI"
