#:schema node_modules/wrangler/config-schema.json
name                   = "demo-ai-db-query"
compatibility_date     = "2024-11-12"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags    = ["nodejs_compat"]

[ai]
binding = "AI"

[[vectorize]]
binding    = "VECTORIZE"
index_name = "demo-ai-db-query-vector"

[[d1_databases]]
binding       = "DBCHINOOK"
database_name = "sample-db-chinook"
database_id   = "728ddd42-3a55-437e-a66c-cf3afa7a95c6"

[[d1_databases]]
binding       = "DBSAKILA"
database_name = "sample-db-sakila"
database_id   = "ef3efdc5-bb8f-49bf-9a06-8f11b3f7243b"

[[d1_databases]]
binding       = "DBNORTHWIND"
database_name = "sample-db-northwind"
database_id   = "933f6964-a0f7-4bc8-a6ab-d265661eb406"
